### ISSUE TITLE
WTTB

### ISSUE THREAD

**Issue by Wit3** [codeat3/blade-google-material-design-icons#22]
Hi, when i install this package, the Waiting for server response increase of 1.7 seconds. ( every request )
In my deploy pipeline i use the command for cache icon

any suggestion?

**Comment by swapnilsarwe** [comment]
Hey @Wit3 ,

Number of icons in this package could be an issue. 
When you cache it your `bootstrap/cache/blade-icons.php` file would have more than 10k+ entries.

Let me run some numbers against other packages with less number of icons.

In the mean time, you can try this [https://github.com/blade-ui-kit/blade-icons#disabling-components](https://github.com/blade-ui-kit/blade-icons#disabling-components) if you are not using directive or helpers in your blade files. It could help a bit in improvising the performance.

**Comment by Wit3** [comment]
> Hey @Wit3 ,
> 
> Number of icons in this package could be an issue. When you cache it your `bootstrap/cache/blade-icons.php` file would have more than 10k+ entries.
> 
> Let me run some numbers against other packages with less number of icons.
> 
> In the mean time, you can try this https://github.com/blade-ui-kit/blade-icons#disabling-components if you are using only directive or helpers in your blade files. It could help a bit in improvising the performance.

Thanks @swapnilsarwe

**Comment by swapnilsarwe** [comment]
Hey @Wit3 ,

I did not get much time to check the issue in details, 
in the meantime - did disabling component help in any way ?

**Comment by Wit3** [comment]
No problem @swapnilsarwe.
When i have time free i'll try to investigate, but for now i've removed this icon set 'cause i can't remove all component render 😖 
Thanks dude

**Comment by arwinvdv** [comment]
Maybe let this issue open till it is fixed so others can see that it is still a problem? Same issue here
