### ISSUE TITLE
Icons missing?

### ISSUE THREAD

**Issue by martin-ro** [codeat3/blade-google-material-design-icons#3]
Some icons like https://fonts.google.com/icons?icon.query=video+camera+front seem to be missing or do i use them wrong?

```html
<x-gmdi-video-camera-front class="h-6 w-6"/>
```

```php
Unable to locate a class or view for component [gmdi-video-camera-front].
```

Also some variant like outline (https://fonts.google.com/icons?icon.query=voice+chat) are not working:

```html
<x-gmdi-voice-chat class="h-6 w-6"/>
```

**Comment by swapnilsarwe** [comment]
@martin-ro 
we were planning to follow the release cycle of [https://github.com/google/material-design-icons/](https://github.com/google/material-design-icons/), assuming that only what gets released is available on website[fonts.google.com](https://fonts.google.com/). The last release was in Sep 2020 which do not have the icons you have mentioned.

You can update your composer dependency to `"codeat3/blade-google-material-design-icons": "dev-master"` which is an Unreleased version and which has all the icons which seems to be missing from the released version (https://github.com/codeat3/blade-google-material-design-icons/releases/tag/0.4.0).

Let me cross check few things, if fonts.google.com is not following the release cycle then we can change our release policy, and you would have all the latest icons without waiting for parent repo to tag a release.

**Comment by swapnilsarwe** [comment]
You can update your package to `1.2.2` to take benefit of all the new icons. 

From now on we won't wait for release and sync with the latest commits.
