### ISSUE TITLE
Unable to locate a class or view for component [gmdi-backup-o].

### ISSUE THREAD

**Issue by pablo-gm-teamswipe** [codeat3/blade-google-material-design-icons#6]
Hello, I installed your component on our Laravel 8 project and the `<x-gmdi-backup-o/>` throws an error and says that it is not found. The `<x-gmdi-backup/>` is working as expected. Any ideas?
Thanks!!

**Comment by swapnilsarwe** [comment]
Kindly update the package to latest version & this should work.
Thanks for reporting.
